//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidadaprobacion
    {
        public Nullable<bool> PresupuestoFirmado { get; set; }
        public Nullable<bool> OrdenCompra { get; set; }
        public Nullable<bool> Otro { get; set; }
        public string DescripcionOtro { get; set; }
        public int PK_ContabilidadID { get; set; }
    
        public virtual contabilidad contabilidad { get; set; }
    }
}
