//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidadfacturacion
    {
        public int PK_FacturacionID { get; set; }
        public Nullable<int> NumeroCuota { get; set; }
        public Nullable<int> NumeroFactura { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> PK_ContabilidadID { get; set; }
    
        public virtual contabilidad contabilidad { get; set; }
    }
}
