//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad
    {
        public contabilidad()
        {
            this.contabilidadfacturacion = new HashSet<contabilidadfacturacion>();
            this.operaciones = new HashSet<operaciones>();
        }
    
        public int PK_ContabilidadID { get; set; }
        public string Direccion { get; set; }
        public string PersonaAprobacion { get; set; }
        public string TelefonoContacto { get; set; }
        public Nullable<int> PK_Cotizacion_ID { get; set; }
        public string Vendedor { get; set; }
        public Nullable<System.DateTime> FechaEjecucion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public int GuiaDespacho { get; set; }
        public Nullable<int> Factura { get; set; }
        public Nullable<int> MesFacturacion { get; set; }
        public Nullable<int> ComisionVendedor { get; set; }
        public Nullable<int> ComisionOtros { get; set; }
    
        public virtual cotizacion cotizacion { get; set; }
        public virtual ICollection<contabilidadfacturacion> contabilidadfacturacion { get; set; }
        public virtual contabilidaddescuentos contabilidaddescuentos { get; set; }
        public virtual contabilidadformapago contabilidadformapago { get; set; }
        public virtual contabilidadaprobacion contabilidadaprobacion { get; set; }
        public virtual ICollection<operaciones> operaciones { get; set; }
    }
}
