//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizaciontrabajoterceros
    {
        public int CotizacionTercerosID { get; set; }
        public string Terceros { get; set; }
        public Nullable<decimal> ValorTerceros { get; set; }
        public Nullable<int> PK_Cotizacion_ID { get; set; }
    
        public virtual cotizacion cotizacion { get; set; }
    }
}
