//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacionrepuesto
    {
        public int CotizacionRepuestoID { get; set; }
        public string Repuesto { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> HoraParHombre { get; set; }
        public Nullable<int> PK_Cotizacion_ID { get; set; }
    
        public virtual cotizacion cotizacion { get; set; }
    }
}
