//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_sertecEntities : DbContext
    {
        public bd_sertecEntities()
            : base("name=bd_sertecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<contabilidad> contabilidad { get; set; }
        public DbSet<contabilidadaprobacion> contabilidadaprobacion { get; set; }
        public DbSet<contabilidaddescuentos> contabilidaddescuentos { get; set; }
        public DbSet<contabilidadfacturacion> contabilidadfacturacion { get; set; }
        public DbSet<contabilidadformapago> contabilidadformapago { get; set; }
        public DbSet<cotizacion> cotizacion { get; set; }
        public DbSet<cotizacionrepuesto> cotizacionrepuesto { get; set; }
        public DbSet<cotizaciontrabajoterceros> cotizaciontrabajoterceros { get; set; }
        public DbSet<operaciones> operaciones { get; set; }
        public DbSet<persona> persona { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
