//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_orden_trabajo_repuesto_reparacion
    {
        public int PK_Presupuesto_OC_Rep_id { get; set; }
        public int Presupuesto_Orden_Trabajo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Codigo { get; set; }
    
        public virtual presupuesto_orden_trabajo presupuesto_orden_trabajo1 { get; set; }
    }
}
